coverage:
  status:
    changes:
      default:
        target: auto
        informational: true
    project:
      default:
        target: auto
        informational: true
    patch:
      default:
        target: auto
        informational: true

# Ignore files that are covered by browser tests (Playwright) rather than unit tests
ignore:
  - 'app/pages/**/*'
  - 'app/layouts/**/*'

comment:
  layout: 'reach,diff,flags,tree,components,tests,build'
  behavior: default
  require_changes: false
